### ISSUE TITLE
Diaphora 3.0: Polishing and New Features

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#193]
This is a list of things that must be fixed, reviewed, potentially refactored, etc... This list doesn't correspond to the currently published version of Diaphora, it only affect the currently unpublished in development version.

- [x] Remove wrong heuristics.
- [x] Probably a typo in CBinDiff.check_ratio() #177.
- [x] Potential issue: row_is_importable may not be checking names #179.
- [x] Importability for global variables in certain cases is significantly diminished #180. 
- [x] Confusion about function: find_matches_in_hole #191.
- [x] Move out from experimental heuristics that should not be experimental.
- [X] Create a testing suite: https://github.com/joxeankoret/diaphora/issues/66
- [X] Support to find and export Compilation Units
- [X] Support to match functions in Compilation Units.
- [X] Collapse Compilation Units that are the same, do not break them into slices.
- [X] Add support for parallelism in the testing suite.
- [X] Move to ‘Unreliable’ heuristics that don’t find anything in the testing suite.
- [x] Add proper support for multiple matches.
- [x] Support to match whole Compilation Units.
- [x] Fix multimatches related bugs.
- [x] Use pseudo-code instructions (diffing names) for finding matches (and later on importing symbols).
- [x] Profile exporting & diffing to try to make it a bit faster wherever it’s possible and makes sense.
- [x] Use Python's [standard logging](https://docs.python.org/3/howto/logging.html) library.
- [x] BUG: Python's difflib is excessively slow.
- [x] BUG: Deleting matches is broken.
- [x] BUG: Multimatches are broken again, they are being shown again.
- [x] BUG: Multimatches are considering even functions with the same name!
- [x] Launch heuristics that might block the GUI in a dedicated thread.
- [x] BUG: Finding matches between "gaps" is so utter wrong.
- [x] Resolve multimatches for "Local affine functions" by following the logic that compilers put functions in order and they should, overall, appear in order.
- [x] Add GUI support for diffing microcode in plain text and in a graph (pretty useful for diffing in a graph different architectures).
- [X] BUG: Since the logic to handle choosers changed, the option "Add Manual Match" is broken.
- [X] Add microcode based heuristics using both plain assembly and graphs.
- [x] Improve significantly the comparison function `check_ratio`.
- [x] All functions that make sense to be used from an external tool using Diaphora should be wrapped up so people can use them directly instead of issuing SQL queries, like what @jpsnyder mentioned about having to reimplement `check_callgraph`.
- [x] Add a configuration file (diaphora_config.py) for anything that should be user defined (like diffing colours, what is considered a big database, timeouts, etc...).
- [x] Publish the testing suite.
- [x] Make Diaphora more "importable" friendly. Possibly by creating a package (if it makes sense at all).
- [x] Add the tested additional comparisons (internally called `deep ratios`) to `check_ratio()` instead of doing extra passes at the end. This should remove lots of multimatches.
- [x] Run default scripts when none is selected to enhance specific modes (i.e., to find potential vulnerabilities fixed when patch diffing is detected).
- [x] Using the multimatches list try to find the best solution using other heuristics.

**Comment by joxeankoret** [comment]
Only 16 tasks remaining!!1!
![image](https://user-images.githubusercontent.com/2945834/219659525-c79801a7-f265-4d41-8d68-892dea0602e7.png)
