### ISSUE TITLE
Diaphora remaining issues

### ISSUE THREAD

**Issue by joxeankoret** [joxeankoret/diaphora#273]
This is a list of these forever existing bugs/features/whatever in Diaphora:

- [ ] Apply structures and enumerations to assembly when importing #100.
- [ ] Import variable names too #141.
- [ ] Try, for n-th time, to fix this bug: https://github.com/joxeankoret/diaphora/issues/13.
- [ ] Add an option to find the (potentially) best match for an unmatched function.
- [ ] BUG: When diffing in the command line in parallel results aren’t guaranteed because of parallelism problems!!!

**Comment by joxeankoret** [comment]
And I fixed one of these, finally, with 3.1.2, but I failed to mark it as done.
